trigger: none

parameters:

  - name: imageTag
    displayName: Docker Image Tag
    type: string
    default: latest

  - name: boldbiPackage
    displayName: BoldBI Package
    type: string
    default: https://s3.amazonaws.com/files2.syncfusion.com/Installs/BoldBI/07-08-2026/BoldBIServer_Linux_Docker_16.2.5_08072026_091439.zip

  - name: environment
    displayName: Environment
    type: string
    default: dev
    values:
      - dev
      - production

stages:

- stage: Build
  jobs:

  - job: DockerBuild
    pool:
      name: boldbi-self-host-build-testing-agent

    steps:

    #################################################
    # Validate Tag
    #################################################

    - bash: |
        TAG="${{ parameters.imageTag }}"

        if [[ ! "$TAG" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$ ]]; then
          echo "Invalid Docker image tag: $TAG"
          exit 1
        fi

        echo "Image tag validation successful"
      displayName: Validate image tag

    #################################################
    # Repository Selection
    #################################################

    - bash: |

        if [ "${{ parameters.environment }}" = "dev" ]; then
          REPO="syncfusion/dev-boldbi-docker"
        else
          REPO="syncfusion/boldbi"
        fi

        echo "##vso[task.setvariable variable=REPOSITORY]$REPO"

      displayName: Set Docker Repository

    #################################################
    # Azure Login
    #################################################

    - bash: |
        echo "Logging into Azure..."

        az login \
          --service-principal \
          -u "$(AZURE_CLIENT_ID)" \
          -p "$(AZURE_CLIENT_SECRET)" \
          --tenant "$(AZURE_TENANT_ID)"

        az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
        IMAGE_ID="/subscriptions/43ad974e-d325-4d50-bcb6-afd2b4999892/resourceGroups/testing/providers/Microsoft.Compute/galleries/boldbi/images/arm64/versions/1.0.0"
        echo "Creating VM..."

        az vm create \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --image "$IMAGE_ID" \
          --size "Standard_D2ps_v5" \
          --vnet-name "vnet-centralindia" \
          --subnet "default" \
          --public-ip-address "" \
          --nsg "" \
          --admin-username azureuser \
          --generate-ssh-keys

        echo "Waiting for VM provisioning..."

        az vm wait \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --created

        echo "Getting private IP..."

        ARM64_PRIVATE_IP=$(az vm list-ip-addresses \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --query "[0].virtualMachine.network.privateIpAddresses[0]" \
          -o tsv)
          
        AMD64_PRIVATE_IP=$(hostname -I | awk '{print $1}')

        echo "================================="
        echo "VM Name    : $(VM_NAME)"
        echo "Arm64 Private IP : $ARM64_PRIVATE_IP"
        echo "Amd64 Private IP : $AMD64_PRIVATE_IP"
        echo "================================="

        echo "##vso[task.setvariable variable=arm64_vm_private_ip]$ARM64_PRIVATE_IP"
        echo "##vso[task.setvariable variable=amd64_vm_private_ip]$AMD64_PRIVATE_IP"

        # Validate IPs
        if [ -z "$ARM64_PRIVATE_IP" ] || [ -z "$AMD64_PRIVATE_IP" ]; then
          echo "ERROR: One or more IP addresses could not be retrieved."
          exit 1
        fi
      displayName: Azure Login

    #################################################
    # Download Package
    #################################################

    - bash: |
        sudo apt-get update
        sudo apt-get install ca-certificates curl zip -y
        wget ${{ parameters.boldbiPackage }}
        unzip BoldBI*.zip
        cd BoldBIServer-Linux
        wget https://raw.githubusercontent.com/mohamedasme-sf4303/temp-code/refs/heads/main/boldbi-manifets.txt
        ls

      displayName: Download Package

    #################################################
    # Docker Login
    #################################################

    - bash: |
        echo "$(DOCKER_PASSWORD)" | docker login \
          -u "$(DOCKER_USERNAME)" \
          --password-stdin
      displayName: Docker Login

    #################################################
    # Selfhost Build
    #################################################

    - bash: |

        docker buildx create \
          --name boldbi-builder \
          --driver remote \
          tcp://$(amd64_vm_private_ip):1234

        docker buildx create \
          --append \
          --name boldbi-builder \
          --driver remote \
          tcp://$(arm64_vm_private_ip):1234

        docker buildx use boldbi-builder

        docker buildx inspect --bootstrap

        IMAGE="$(REPOSITORY):${{ parameters.imageTag }}"

        cd BoldBIServer-Linux

        docker buildx build \
          --builder boldbi-builder \
          --platform linux/amd64,linux/arm64 \
          -t "$IMAGE" \
          -f boldbi-manifets.txt .

      displayName: Selfhost Buildx

    #################################################
    # Stop VMs
    #################################################

    - bash: |
        az vm delete \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --yes
      displayName: Delete VMs
