trigger: none

variables:
  ADO_ORG_URL: https://dev.azure.com/bold-bi
  ADO_PROJECT: build
  VARIABLE_GROUP_ID: 70

parameters:

- name: imageTag
  displayName: Docker Image Tag
  type: string
  default: latest

- name: boldbiPackage
  displayName: BoldBI Package
  type: string
  default: https://s3.amazonaws.com/files2.syncfusion.com/Installs/BoldBI/07-08-2026/BoldBIServer_Linux_Docker_16.2.5_08072026_091439.zip

- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
    - dev
    - production

stages:

- stage: Build

  jobs:

  ####################################################################
  # ARM64 JOB
  ####################################################################

  - job: Arm64Job

    displayName: ARM64 IP + Wait For Image

    pool:
      name: boldbi-sefl-host-arm64-vmss

    steps:

    #################################################
    # Validate Tag
    #################################################

    - bash: |

        TAG="${{ parameters.imageTag }}"

        if [[ ! "$TAG" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$ ]]; then
          echo "Invalid Docker image tag: $TAG"
          exit 1
        fi

        echo "Image tag validation successful"

      displayName: Validate Tag

    #################################################
    # Save ARM64 IP
    #################################################

    - bash: |

        ARM64_IP=$(hostname -I | awk '{print $1}')

        if [ -z "$ARM64_IP" ]; then
          echo "ARM64 IP not found"
          exit 1
        fi

        VAR_NAME="ARM64_IP_$(Build.BuildId)"

        echo "Saving Variable: $VAR_NAME"
        echo "ARM64 IP: $ARM64_IP"

        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

        az pipelines variable-group variable create \
          --group-id $(VARIABLE_GROUP_ID) \
          --name "$VAR_NAME" \
          --value "$ARM64_IP"

        echo "ARM64 IP stored"

      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      displayName: Save ARM64 IP
      
    #################################################
    # Verify Multi-Arch Image
    #################################################
    
    - bash: |
    
        if [ "${{ parameters.environment }}" = "dev" ]; then
          REPO="syncfusion/dev-boldbi-docker"
        else
          REPO="syncfusion/boldbi"
        fi
    
        IMAGE="${REPO}:${{ parameters.imageTag }}"
    
        echo "$(DOCKER_PASSWORD)" | docker login \
          -u "$(DOCKER_USERNAME)" \
          --password-stdin
    
        echo "================================="
        echo "Waiting for image: $IMAGE"
        echo "Checking:"
        echo " - linux/amd64"
        echo " - linux/arm64"
        echo "================================="
    
        for i in {1..30}
        do
    
          echo "Attempt $i/30"
    
          OUTPUT=$(docker buildx imagetools inspect "$IMAGE" 2>/dev/null)
    
          AMD64_FOUND=$(echo "$OUTPUT" | grep -c "linux/amd64")
          ARM64_FOUND=$(echo "$OUTPUT" | grep -c "linux/arm64")
    
          echo "amd64 count : $AMD64_FOUND"
          echo "arm64 count : $ARM64_FOUND"
    
          if [ "$AMD64_FOUND" -gt 0 ] && [ "$ARM64_FOUND" -gt 0 ]; then
    
            echo ""
            echo "================================="
            echo "SUCCESS: Multi-Arch Image Found"
            echo "Image: $IMAGE"
            echo "linux/amd64 : OK"
            echo "linux/arm64 : OK"
            echo "================================="
    
            exit 0
    
          fi
    
          echo "Required architectures not available yet..."
          sleep 60
    
        done
    
        echo ""
        echo "================================="
        echo "ERROR: Multi-Arch Image Not Found"
        echo "Image: $IMAGE"
        exit 1
      displayName: Wait For Image
   

  ####################################################################
  # AMD64 JOB
  ####################################################################

  - job: DockerBuild

    displayName: Build Docker Image

    pool:
      name: boldbi-sefl-host-amd64-vmss

    steps:

    #################################################
    # Wait for ARM64 IP
    #################################################

    - bash: |

        VAR_NAME="ARM64_IP_$(Build.BuildId)"
        sudo apt-get update
        sudo apt-get install -y jq
        az devops configure \
          --defaults \
          organization="$(ADO_ORG_URL)" \
          project="$(ADO_PROJECT)"

        echo "Waiting for ARM64 IP..."

        for i in {1..30}
        do

          ARM64_IP=$(az pipelines variable-group variable list \
            --group-id $(VARIABLE_GROUP_ID) \
            --output json \
            | jq -r --arg v "$VAR_NAME" '.[$v].value // empty')

          if [ -n "$ARM64_IP" ]; then

            echo "ARM64 IP Found: $ARM64_IP"

            echo "##vso[task.setvariable variable=arm64_vm_private_ip]$ARM64_IP"

            exit 0

          fi

          echo "Waiting..."
          sleep 10

        done

        echo "ARM64 IP not found within 5 minutes"
        exit 1

      env:
        AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      displayName: Wait For ARM64 IP

    #################################################
    # Get Current AMD64 VM IP
    #################################################

    - bash: |

        AMD64_IP=$(hostname -I | awk '{print $1}')

        if [ -z "$AMD64_IP" ]; then
          echo "AMD64 IP not found"
          exit 1
        fi

        echo "AMD64 IP: $AMD64_IP"

        echo "##vso[task.setvariable variable=amd64_vm_private_ip]$AMD64_IP"

      displayName: Get AMD64 VM IP

    #################################################
    # Repository Selection
    #################################################

    - bash: |

        if [ "${{ parameters.environment }}" = "dev" ]; then
          REPO="syncfusion/dev-boldbi-docker"
        else
          REPO="syncfusion/boldbi"
        fi

        echo "##vso[task.setvariable variable=REPOSITORY]$REPO"

      displayName: Set Docker Repository

    #################################################
    # Download Package
    #################################################

    - bash: |

        sudo apt-get update

        sudo apt-get install -y \
          ca-certificates \
          curl \
          zip \
          jq

        wget "${{ parameters.boldbiPackage }}"

        unzip BoldBI*.zip

        cd BoldBIServer-Linux

        wget https://raw.githubusercontent.com/mohamedasme-sf4303/temp-code/refs/heads/main/boldbi-manifets.txt

      displayName: Download Package

    #################################################
    # Docker Login
    #################################################

    - bash: |

        echo "$(DOCKER_PASSWORD)" | docker login \
          -u "$(DOCKER_USERNAME)" \
          --password-stdin

      displayName: Docker Login

    #################################################
    # Wait For ARM64 BuildKit
    #################################################

    - bash: |

        echo "Waiting for ARM64 BuildKit..."

        for i in {1..30}
        do

          if nc -z $(arm64_vm_private_ip) 1234; then
            echo "BuildKit reachable"
            exit 0
          fi

          echo "Waiting BuildKit..."
          sleep 10

        done

        echo "BuildKit not reachable"
        exit 1

      displayName: Wait For BuildKit

    #################################################
    # Buildx
    #################################################

    - bash: |

        docker buildx rm boldbi-builder || true

        echo "AMD64 IP : $(amd64_vm_private_ip)"
        echo "ARM64 IP : $(arm64_vm_private_ip)"

        docker buildx create \
          --name boldbi-builder \
          --driver remote \
          tcp://$(amd64_vm_private_ip):1234

        docker buildx create \
          --append \
          --name boldbi-builder \
          --driver remote \
          tcp://$(arm64_vm_private_ip):1234

        docker buildx use boldbi-builder

        docker buildx inspect --bootstrap

        IMAGE="$(REPOSITORY):${{ parameters.imageTag }}"

        cd BoldBIServer-Linux

        docker buildx build \
          --builder boldbi-builder \
          --platform linux/amd64,linux/arm64 \
          -t "$IMAGE" \
          -f boldbi-manifets.txt \
          --push .

      displayName: Selfhost Buildx
