trigger: none

pool:
  name: boldbi-sefl-host-amd64-vmss

variables:
  VM_NAME: test-vm-$(Build.BuildId)

steps:
  - bash: |

        echo "Logging into Azure..."

        az login \
          --service-principal \
          -u "$(AZURE_CLIENT_ID)" \
          -p "$(AZURE_CLIENT_SECRET)" \
          --tenant "$(AZURE_TENANT_ID)"

        az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"
        IMAGE_ID="/subscriptions/43ad974e-d325-4d50-bcb6-afd2b4999892/resourceGroups/testing/providers/Microsoft.Compute/galleries/boldbi/images/arm64/versions/1.0.0"
        echo "Creating VM..."

        az vm create \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --image "$IMAGE_ID" \
          --size "Standard_D2ps_v5" \
          --vnet-name "vnet-centralindia" \
          --subnet "default" \
          --public-ip-address "" \
          --nsg "" \
          --admin-username azureuser \
          --generate-ssh-keys

        echo "Waiting for VM provisioning..."

        az vm wait \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --created

        echo "Getting private IP..."

        PRIVATE_IP=$(az vm list-ip-addresses \
          --resource-group "testing" \
          --name "$(VM_NAME)" \
          --query "[0].virtualMachine.network.privateIpAddresses[0]" \
          -o tsv)

        echo "================================="
        echo "VM Name    : $(VM_NAME)"
        echo "Private IP : $PRIVATE_IP"
        echo "================================="

    displayName: Create new VM

  - bash: |

      # echo "Deleting VM $(VM_NAME)..."

      # az login \
      #   --service-principal \
      #   -u "$(AZURE_CLIENT_ID)" \
      #   -p "$(AZURE_CLIENT_SECRET)" \
      #   --tenant "$(AZURE_TENANT_ID)"

      # az account set --subscription "$(AZURE_SUBSCRIPTION_ID)"

      az vm delete \
        --resource-group "testing" \
        --name "$(VM_NAME)" \
        --yes

      echo "VM deleted successfully."

    displayName: Delete VM
    condition: always()